scopes:
  workspaces: packages/*
  root: /

scripts:
  lint:
    command: "eslint src/** --no-error-on-unmatched-pattern"
    scope: workspaces
  version:
    command: "npm version [newversion]"
    scope: workspaces
  build:
    command:
      - "lint"
      - "$ npm run build"
    scope: *
