language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
branches:
  only:
    - master
    - v4
cache:
  directories:
    - "$HOME/.npm"
    - node_modules
services:
  - postgresql
env:
  - PGDATABASE=travis_ci_test
before_script:
  - psql -c 'create database travis_ci_test;' -d postgres -U postgres
install:
  - "npm install npm -g"
  - "npm install"
script:
  - "npm run test"
after_script:
  - "npm install coveralls && cat ./coverage/lcov.info | coveralls"
