import { Column, DataType, Entity, Link, PrimaryKey } from '@sqb/connect';
import type { Grandchild } from './grandchild.entity.js';
import { Parent } from './parent.entity.js';

@Entity('children')
export class Child {
  @PrimaryKey()
  @Column({ dataType: DataType.INTEGER, autoGenerated: 'increment' })
  declare id: number;

  @Column()
  declare name: string;

  @Column({ fieldName: 'parent_id' })
  declare parentId: number;

  @Link({ exclusive: true })
  declare parent: Parent;

  @(Link({ exclusive: true }).toMany(
    async () => (await import('./grandchild.entity.js')).Grandchild,
    { sourceKey: 'id', targetKey: 'childId' },
  ))
  declare grandchildren: Grandchild[];
}
