import { Column, DataType, Entity, Link, PrimaryKey } from '@sqb/connect';
import { Child } from './child.entity.js';

@Entity('grandchildren')
export class Grandchild {
  @PrimaryKey()
  @Column({ dataType: DataType.INTEGER, autoGenerated: 'increment' })
  declare id: number;

  @Column()
  declare name: string;

  @Column({ fieldName: 'child_id' })
  declare childId: number;

  @Link({ exclusive: true })
  declare child: Child;
}
