import { Column, DataType, Entity, Link, PrimaryKey } from '@sqb/connect';
import type { Child } from './child.entity.js';

@Entity('parents')
export class Parent {
  @PrimaryKey()
  @Column({ dataType: DataType.INTEGER, autoGenerated: 'increment' })
  declare id: number;

  @Column()
  declare name: string;

  @(Link({ exclusive: true }).toOne(
    async () => (await import('./child.entity.js')).Child,
    { sourceKey: 'id', targetKey: 'parentId' },
  ))
  declare child: Child;
}
