language: node_js
node_js:
  - '10'
branches:
  only:
    - master
    - v4
dist: xenial
cache:
  directories:
    - '$HOME/.npm'
    - node_modules
env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE
  - ORAUSER=travis
  - ORAPASSWORD=travis
before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
install:
  - 'npm install'
script:
  - 'npm run-script travis-cover'
after_script:
  - 'npm install coveralls && cat ./coverage/lcov.info | coveralls'
